from comtradehandlers import writer


import csv
import datetime
"""
The following code simulates phasor data within the COMTRADE format. See the following for more information:
    PSRC H8 Application of COMTRADE for Synchrophasor Data
    Approved by IEEE PSRC Subcommittee H on May 13, 2010 as a PSRC Report
    Schema for Phasor Data Using the COMTRADE File Standard
"""
start_time = datetime.datetime.now()
trigger_time = start_time + datetime.timedelta(milliseconds=20)
comtradeWriter = writer.ComtradeWriter("test2.cfg", start_time, trigger_time, rev_year="1999",rec_dev_id=250)

created_id = comtradeWriter.add_digital_channel("RELAY1", 0, 0, 0)
print("Created new digital channel " + str(created_id))

created_id = comtradeWriter.add_digital_channel("RELAY2", 0, 0, 0)
print("Created new digital channel " + str(created_id))

# A Current Phasor
created_id = comtradeWriter.add_analog_channel("LK:INC:Am", "Am", "Inom", uu="A", skew=0, min=0, max=250, primary=1,
                                               secondary=1)
print("Created new analog channel " + str(created_id))

created_id = comtradeWriter.add_analog_channel("LK:INC:Aa", "Aa", "", uu="rad", skew=0, min=0, max=7, primary=1,
                                               secondary=1)
print("Created new analog channel " + str(created_id))

# B Current Phasor
created_id = comtradeWriter.add_analog_channel("LK:INC:Bm", "Bm", "Inom", uu="A", skew=0, min=0, max=250, primary=1,
                                               secondary=1)
print("Created new analog channel " + str(created_id))

created_id = comtradeWriter.add_analog_channel("LK:INC:Ba", "Ba", "", uu="rad", skew=0, min=0, max=7, primary=1,
                                               secondary=1)
print("Created new analog channel " + str(created_id))

# C Current Phasor
created_id = comtradeWriter.add_analog_channel("LK:INC:Cm", "Cm", "Inom", uu="A", skew=0, min=0, max=250, primary=1,
                                               secondary=1)
print("Created new analog channel " + str(created_id))

created_id = comtradeWriter.add_analog_channel("LK:INC:Ca", "Ca", "", uu="rad", skew=0, min=0, max=7, primary=1,
                                               secondary=1)
print("Created new analog channel " + str(created_id))

# frequency
created_id = comtradeWriter.add_analog_channel("LK:INC:F", "F", "", uu="hz", a=0.001, b=50, skew=0, min=0, max=60,
                                               primary=1, secondary=1)
print("Created new analog channel " + str(created_id))

# ROCOF
created_id = comtradeWriter.add_analog_channel("LK:INC:df", "df", "", uu="hz", a=0.01, b=0, skew=0, min=-50, max=50,
                                               primary=1, secondary=1)
print("Created new analog channel " + str(created_id))

with open('rawtestdata.csv', 'r') as csvfile:
    datareader = csv.reader(csvfile, delimiter=',', quotechar='|')
    next(datareader, None)  # skip the header
    for row in datareader:
        comtradeWriter.add_sample_record(row[0],
                                         [row[1], row[2], row[3], row[4], row[5], row[6], row[7], row[8]],
                                         [row[9], row[10]])

comtradeWriter.set_header_content("Data generated by Liam Relihan from a CSV file. Enjoy!")

comtradeWriter.finalize()

"""
SECOND FILE
"""

start_time = datetime.datetime.now()
trigger_time = start_time + datetime.timedelta(milliseconds=20)
comtradeWriter2 = writer.ComtradeWriter("test3.cfg", start_time, trigger_time, rev_year="1999",rec_dev_id=250)

created_id = comtradeWriter2.add_digital_channel("RELAY1", 0, 0, 0)
print("Created new digital channel " + str(created_id))

created_id = comtradeWriter2.add_digital_channel("RELAY2", 0, 0, 0)
print("Created new digital channel " + str(created_id))



# A Current
created_id = comtradeWriter2.add_analog_channel("IA", "A", "I", uu="A", skew=0, min=-500, max=500, primary=1,
                                               secondary=1)
print("Created new analog channel " + str(created_id))

# B Current
created_id = comtradeWriter2.add_analog_channel("IB", "B", "I", uu="A", skew=0, min=-500, max=500, primary=1,
                                               secondary=1)
print("Created new analog channel " + str(created_id))

# C Current
created_id = comtradeWriter2.add_analog_channel("IC", "C", "I", uu="A", skew=0, min=-500, max=500, primary=1,
                                               secondary=1)
print("Created new analog channel " + str(created_id))


with open('outdata.csv', 'r') as csvfile:
    datareader = csv.reader(csvfile, delimiter=',', quotechar='|')
    next(datareader, None)  # skip the header
    for row in datareader:
        print(" 0="+row[0]+" 1="+row[1]+" 2="+row[2]+" 3="+row[3]+" 4="+row[4]+" 5="+row[5])
        comtradeWriter2.add_sample_record(row[0],
                                         [row[1], row[2], row[3]],
                                         [row[4], row[5]])

comtradeWriter2.set_header_content("Data generated by Liam Relihan from a CSV file. Enjoy!")

comtradeWriter2.finalize()